version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todos_db
    ports:
      - "5432:5432"

  backend:
    build: ./todo-backend
    container_name: todo_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: todos_db
    depends_on:
      - db

  frontend:
    build: ./todo-frontend
    container_name: todo_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
